### ISSUE TITLE
xxxFields Classes Not Always Generated

### ISSUE THREAD

**Issue by ghost** [cmelchior/realmfieldnameshelper#10]
I've been using your library to great success. However, it seems to have randomly stopped generating the Fields classes. 

Gradle version: 2.2.0
Realm version: 2.1.1
Gradle tasks used: clean build, clean assembleDebug

**Comment by Zhuinden** [comment]
do you use android-apt?

What is your plugin apply order in build gradle?

**Comment by cmelchior** [comment]
Closing this since it cannot be reproduced.
