### ISSUE TITLE
Does this work with 'implements RealmModel'

### ISSUE THREAD

**Issue by bobbyflowstate** [cmelchior/realmfieldnameshelper#11]
Hi there, I want to use your library, but I was wondering if this would work with POJO's that implement the RealmModel interface instead of extending RealmModel. I am traveling and don't have a chance to test this out myself. Will try it out myself tomorrow if you don't get to me before then.

**Comment by Zhuinden** [comment]
If you use `@RealmClass` annotation then it should

**Comment by cmelchior** [comment]
What @Zhuinden said. The annotation processor just picks up all classes with the `@RealmClass` annotation. So it should work.
