### ISSUE TITLE
Could not find method apt

### ISSUE THREAD

**Issue by ngoohebi** [cmelchior/realmfieldnameshelper#13]
Error:(49, 0) Could not find method apt() for arguments [dk.ilios:realmfieldnameshelper:1.1.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Switch to annotationProcessor?

**Comment by Zhuinden** [comment]
well you can either use `android-apt` plugin, or `annotationProcessor` scope

**Comment by AnixPasBesoin** [comment]
Add the android-apt plugin as [EpicPandaForce](https://github.com/Zhuinden) suggested. Here's a [link](https://bitbucket.org/hvisser/android-apt). Just follow the instructions.

**Comment by cmelchior** [comment]
Answered by @Zhuinden and @AnixPasBesoin. Closing.
