### ISSUE TITLE
NPE if there is no @RealmClass in the project

### ISSUE THREAD

**Issue by Zhuinden** [cmelchior/realmfieldnameshelper#14]
Caused by: java.lang.NullPointerException
        at dk.ilios.realmfieldnames.RealmFieldNamesProcessor.init(RealmFieldNamesProcessor.java:54)

**Comment by cmelchior** [comment]
This seems more about the annotation processor crashing if Realm isn't part of the project. At least I couldn't reproduce this if no model classes existed, but it did crash if Realm wasn't on the classpath.

**Comment by Zhuinden** [comment]
Ah. Sorry about the false issue then. 

But yes, the project also didn't have Realm plugin.
