### ISSUE TITLE
Example doesn't use generated field

### ISSUE THREAD

**Issue by Zhuinden** [cmelchior/realmfieldnameshelper#2]
In [this line](https://github.com/cmelchior/realmfieldnameshelper/blob/master/example/src/main/java/dk/ilios/example/realmfieldnames/MainActivity.java#L23), `"name"` is given instead of `PersonFields.NAME`

**Comment by cmelchior** [comment]
Yup. I still need to do proper cleanup there and a few other places. Got side-tracked trying to get Travis to work.

**Comment by Zhuinden** [comment]
Fair enough, I just figured I'd note it because I saw it :)

**Comment by cmelchior** [comment]
No problem. Hard to know unless you also have access to the `TODO.txt` sitting on my laptop :)

**Comment by Zhuinden** [comment]
That'd be creepy o-o
