### ISSUE TITLE
Add support for @LinkingObjects("name") backlinks name

### ISSUE THREAD

**Issue by ursusursus** [cmelchior/realmfieldnameshelper#22]
Add support for @LinkingObjects("children name in parent") backlinks name, now when I use `@LinkingObjects(ParentFields.CHILDREN.$)` it doesnt compile with 1.1.1

**Comment by cmelchior** [comment]
Unfortunately, this isn't possible since there is no way to control in which order the annotation processors run. So sometimes you might get lucky it works, in most cases, it probably won't :(

Closing

**Comment by filipkowicz** [comment]
@cmelchior shouldn't it wait until other processors do they job. It work somehow with Dagger and AutoFactory - both working as annotation processors
