### ISSUE TITLE
Kotlin Support

### ISSUE THREAD

**Issue by ReginFell** [cmelchior/realmfieldnameshelper#9]
Hi!
Do you have plans to implement kotlin support?

**Comment by cmelchior** [comment]
Is there something that doesn't work in Kotlin? (I haven't tried)

**Comment by thebrokenbar** [comment]
I've came across a bug with Kotlin. 

`Error:java.lang.RuntimeException: java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$VarSymbol cannot be cast to javax.lang.model.element.TypeElement  `

To reproduce: create Kotlin project with Realm and your Library imported with 'kapt'. Create RealmObject class.

**Comment by cmelchior** [comment]
@thebrokenpipe Thanks for reporting this. I can reproduce this as well.
